backend:
  name: git-gateway
  branch: master
# site_url: https://davidanunez.com
media_folder: public/img
public_folder: public
media_library:
  name: netlify
collections:
  - name: pages
    label: Pages
    label_singular: Page
    format: json
    extension: json
    # folder: content/pages
    # create: true
    files:
      - name: home
        label: Home
        file: "content/pages/about.mdx"
    fields:
      - &metaTitle
        name: metaTitle
        label: Meta Title
        widget: string
        pattern:
          - '[^"]{0,60}'
          - Must be 60 or fewer characters long.
      - &metaDescription
        name: metaDescription
        label: Meta Description
        widget: string
        pattern:
          - '[^"]{50,160}'
          - Must be between 50 and 160 characters long.
  - name: articles
    label: Articles
    label_singular: Article
    format: json
    extension: json
    folder: content/articles
    create: true
    fields:
      - *metaTitle
      - *metaDescription
