backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: public
collections:
  - name: pages
    label: Pages
    format: json
    extension: json
    folder: content/pages
  - name: articles
    label: Articles
    format: json
    extension: json
    folder: content/articles
